name: "Go lint"
on: [push, pull_request]

jobs:
  ci:
    name: "CI job"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GolangCI-Lint Action
        uses: matoous/golangci-lint-action@v1.23.3

